### ISSUE TITLE
As a student, I want a menu panel, so I can easily navigate the application.

### ISSUE THREAD

**Issue by totally-innocent-username** [cse442-spring-2020-offering/cse442-semester-project-everything-hertz#5]
<b> Acceptance Test </b> <br>
Test 1:
* Launch UBEventManager application from home screen
* Tap three line menu icon in the top left of the interface
* Ensure the navigation pane is displayed

Test 2:
* Within the navigation pane, ensure the following is displayed:
  * Student name
  * Student picture
  * Home page option
  * Check in to event option
  * Upcoming Events option
  * Log out option

Test 3:
* Make sure clicking all 4 options (Home page, Check in to event, Upcoming Events, and Log out) all link to appropriate pages (with appropriate titles)
 and see that there is a button to see navigation
* When menu button is clicked, it opens a menu with all pages available to be selected
* All options on the menu bring the user to the appropriate page

Test 4:
* Make sure home button (circle in the middle on the bottom of the phone) brings the user back to the home screen of the phone and exits the app

**Comment by nceccarelli** [comment]
<b> Acceptance Test </b> <br>
* Launch application and see that there is a button to see navigation
* When menu button is clicked, it opens a menu with all pages available to be selected
* All options on the menu bring the user to the appropriate page
