### ISSUE TITLE
As a student, I want a log in page, to access the apps main functionality from

### ISSUE THREAD

**Issue by katsemenova** [cse442-spring-2020-offering/cse442-semester-project-everything-hertz#6]
**Acceptance test 1:**

Log in page contains:
* a username input box
* a password input box 
* and a submit button.

**Acceptance test 2:**

1. Able to type in credentials
2. Clicking the submit button takes you to the home page of the app

**Comment by totally-innocent-username** [comment]
Acceptance test 1:
- Log in page contains a username input box, a password input box, and a submit button.

Acceptance test 2:
- Clicking the submit button takes you to the home page of the app
